// Generated 09 Apr 2024 14:57 - Singular Systems Object Generator Version 3.0.000
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using Singular.DataAnnotations;
using System.Data;
using System.Data.SqlClient;


namespace MEWeb.Movies
{
  [Serializable]
  public class ROOrderList
  : SingularReadOnlyListBase<ROOrderList, ROOrder>
  {
    #region " Business Methods "

    public ROOrder GetItem(int OrderID)
    {
      foreach (ROOrder child in this)
      {
        if (child.OrderID == OrderID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "Orders";
    }

    #endregion

    #region " Data Access "

    [Serializable]
    public class Criteria
      : CriteriaBase<Criteria>
    {
      public Criteria()
      {
      }

    }

    public static ROOrderList NewROOrderList()
    {
      return new ROOrderList();
    }

    public ROOrderList()
    {
      // must have parameter-less constructor
    }

    public static ROOrderList GetROOrderList()
    {
      return DataPortal.Fetch<ROOrderList>(new Criteria());
    }

    protected void Fetch(SafeDataReader sdr)
    {
      this.RaiseListChangedEvents = false;
      this.IsReadOnly = false;
      while (sdr.Read())
      {
        this.Add(ROOrder.GetROOrder(sdr));
      }
      this.IsReadOnly = true;
      this.RaiseListChangedEvents = true;
    }

    protected override void DataPortal_Fetch(Object criteria)
    {
      Criteria crit = (Criteria)criteria;
      using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
      {
        cn.Open();
        try
        {
          using (SqlCommand cm = cn.CreateCommand())
          {
            cm.CommandType = CommandType.StoredProcedure;
            cm.CommandText = "GetProcs.getROOrderList";
            using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
            {
              Fetch(sdr);
            }
          }
        }
        finally
        {
          cn.Close();
        }
      }
    }

    #endregion

  }

}