// Generated 11 Jan 2021 20:43 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Accounts
{
  [Serializable]
  public class UserAccountList
   : MEBusinessListBase<UserAccountList, UserAccount>
  {
    #region " Business Methods "

    public UserAccount GetItem(int UserAccountID)
    {
      foreach (UserAccount child in this)
      {
        if (child.UserAccountID == UserAccountID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "User Accounts";
    }

    #endregion

    #region " Data Access "

    [Serializable]
    public class Criteria
      : CriteriaBase<Criteria>
    {
      public int UserID { get; set; }
      public Criteria()
      {
      }

    }

    public static UserAccountList NewUserAccountList()
    {
      return new UserAccountList();
    }

    public UserAccountList()
    {
      // must have parameter-less constructor
    }

    public static UserAccountList GetUserAccountList()
    {
      return DataPortal.Fetch<UserAccountList>(new Criteria());
    }

    public static UserAccountList GetUserAccountList(int userID)
    {
      return DataPortal.Fetch<UserAccountList>(new Criteria { UserID = userID});
    }

    protected void Fetch(SafeDataReader sdr)
    {
      this.RaiseListChangedEvents = false;
      while (sdr.Read())
      {
        this.Add(UserAccount.GetUserAccount(sdr));
      }
      this.RaiseListChangedEvents = true;
    }

    protected override void DataPortal_Fetch(Object criteria)
    {
      Criteria crit = (Criteria)criteria;
      using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
      {
        cn.Open();
        try
        {
          using (SqlCommand cm = cn.CreateCommand())
          {
            cm.CommandType = CommandType.StoredProcedure;
            cm.CommandText = "GetProcs.getUserAccountList";
            cm.Parameters.AddWithValue("@UserID", crit.UserID);
            using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
            {
              Fetch(sdr);
            }
          }
        }
        finally
        {
          cn.Close();
        }
      }
    }

    #endregion

  }

}