// Generated 09 Apr 2024 11:36 - Singular Systems Object Generator Version 3.0.000
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using Singular.DataAnnotations;
using System.Data;
using System.Data.SqlClient;


namespace MEWeb.Movies
{
  [Serializable]
  public class ActivityList
  : SingularBusinessListBase<ActivityList, Activity>
  {
    #region " Business Methods "

    public Activity GetItem(int ActivityID)
    {
      foreach (Activity child in this)
      {
        if (child.ActivityID == ActivityID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "Activitys";
    }

    #endregion

    #region " Data Access "

    [Serializable]
    public class Criteria
      : CriteriaBase<Criteria>
    {
      public Criteria()
      {
      }

    }

    public static ActivityList NewActivityList()
    {
      return new ActivityList();
    }

    public ActivityList()
    {
      // must have parameter-less constructor
    }

    public static ActivityList GetActivityList()
    {
      return DataPortal.Fetch<ActivityList>(new Criteria());
    }

    protected void Fetch(SafeDataReader sdr)
    {
      this.RaiseListChangedEvents = false;
      while (sdr.Read())
      {
        this.Add(Activity.GetActivity(sdr));
      }
      this.RaiseListChangedEvents = true;
    }

    protected override void DataPortal_Fetch(Object criteria)
    {
      Criteria crit = (Criteria)criteria;
      using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
      {
        cn.Open();
        try
        {
          using (SqlCommand cm = cn.CreateCommand())
          {
            cm.CommandType = CommandType.StoredProcedure;
            cm.CommandText = "GetProcs.getActivityList";
            using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
            {
              Fetch(sdr);
            }
          }
        }
        finally
        {
          cn.Close();
        }
      }
    }

    #endregion

  }

}